server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka
  instance:
    instance-id: user-consumer:8004
    prefer-ip-address: true
spring:
  application:
    name: user-consumer
  zipkin:
    base-url: http://localhost:9003
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true

order-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level: info
