server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka
spring:
  application:
    name: person-project-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/persondb
    username: root
    password: ok
mybatis:
  mapper-locations: classpath:mapper/*.xml