
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka
  instance:
    instance-id: person-project-consumer:8002
    prefer-ip-address: true
spring:
  application:
    name: person-project-consumer
